### ISSUE TITLE
Preview: sometimes iframe doesn't load

### ISSUE THREAD

**Issue by jerrywu001** [codesandbox/sandpack#786]
- 1.

Sometimes has no preview result. (mac or windows)

This issue will recur after repeated attempts. (Try 10 times, maybe 3 times this problem occurs)

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/12525415/222061674-df94732f-fc55-4361-aa6c-68aaa40c753c.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/12525415/222061734-e0617fa7-6f11-4779-a5f2-3c4bd0089904.png">

---
- 2.

For: nextjs

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/12525415/222063573-81fdb4bc-008a-4ab8-a7ab-2d51223f976d.png">

**Comment by danilowoz** [comment]
Can you try again? I think it was an issue on the Next.js template, which we fixed on production

**Comment by jerrywu001** [comment]
> Can you try again? I think it was an issue on the Next.js template, which we fixed on production

The two problems mentioned above still exist. **But the template `react, vue, angular` is ok.**

Does it have anything to do with my network's location (china)?

And **My android phone (OnePlus 6T) always has an empty preview.**

**Comment by jerrywu001** [comment]
I add a console.log(`message.type`) to `@codesandbox/client/dist/clients/node/index.mjs`

<img width="608" alt="image" src="https://user-images.githubusercontent.com/12525415/222327512-ab16d405-94e9-46c9-8929-65d35736f65c.png">


- When getting an empty preview, it logs:
 
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/12525415/222326269-f1597401-c163-47b1-8046-2fdc11fc9557.png">

- When everything is ok, it logs:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/12525415/222326664-9772d069-187c-4110-aa5e-550f4fa0b403.png">

**So I guess there has something wrong with init iframe URL (actually the URL is `_blank`)**

<img width="730" alt="image" src="https://user-images.githubusercontent.com/12525415/222326996-86302e4d-f277-42bc-9186-5b3b070f4190.png">


@danilowoz

**Comment by jerrywu001** [comment]
Actually `template react` starts faster than `template vite-react`.🥹

**Comment by danilowoz** [comment]
> should add a timeout error overlay!
Interesting! It should have two timeout overlays: one for the bundler's no response and another for the preview. I'll look at what's going on.

> enable custom the timeout by user 
Let's try to increase all timeouts a bit

> about nextjs preview error
It should be fixed.

> Actually template react starts faster than template vite-react.🥹
Yes, it is. If you only need a simple react project, go for `react` template. But if you want to run Vite, postcss, or any other advanced example, go for vite + react

**Comment by jerrywu001** [comment]
> about nextjs preview error

still exist

**Comment by danilowoz** [comment]
Let's give https://github.com/codesandbox/sandpack/pull/789 a try

**Comment by jerrywu001** [comment]
great. works better now. but still not 100% safe.

we need a preview timeou overlay.

**Comment by danilowoz** [comment]
How this looks for you now? https://sandpack-docs-git-throw-error-timeout-codesandbox1.vercel.app/docs/quickstart

**Comment by jerrywu001** [comment]
> How this looks for you now? https://sandpack-docs-git-throw-error-timeout-codesandbox1.vercel.app/docs/quickstart

great. works better now. but not 100% safe.

we need a preview timeout overlay.

**Comment by danilowoz** [comment]
Well, it should have had a timeout overlay 😄 

Unfortunately, I can't reproduce it, so would you mind screen-recording the next.js template on this link? https://sandpack-docs-fjc9lm193-codesandbox1.vercel.app/docs/quickstart#preview

**Comment by jerrywu001** [comment]
![Screenshot_20230302-202422](https://user-images.githubusercontent.com/12525415/222428243-c7e981a6-87d7-4d85-ae51-42d894ffa905.jpg)

The probability of occurrence is very small

**Comment by jerrywu001** [comment]
![Screenshot_20230302-202422__01](https://user-images.githubusercontent.com/12525415/222429339-51e621d8-9f83-4d1e-9aa5-ed3a349e44e7.jpg)

The probability of occurrence is very small

**Comment by jerrywu001** [comment]
Using traceless window access may occur

Or my network may be unstable.

https://user-images.githubusercontent.com/12525415/222440123-116aa4bd-baeb-4357-868b-fbea07fcb92a.mp4

**Comment by danilowoz** [comment]
Thank you so much @jerrywu001 for reporting this and helping us debug it! I believe I could cover all possible cases on https://github.com/codesandbox/sandpack/pull/792 and it should be fixed.
